name: Terraform Create Or Destroy 

on: 
    workflow_dispatch:
        inputs:
            action:
                type: choice
                description: terraform action to run
                options:
                - apply
                - destroy

jobs:
    terraform-print-action:
        runs-on: ubuntu-latest

        steps:
            - name: Print Terraform action choice
              run: echo ${{ inputs.action }}

    terraform-run-action:
        needs: terraform-print-action
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4.1.5

            - name: Set up AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

            - name: Print action choice
              run: echo ${{ inputs.action }}

            - name: Run terraform init
              run: terraform init
            
            - name: Run terraform plan
              run: terraform plan

            - name: Run terraform ${{ inputs.action }}
              run: echo "terraform ${{ inputs.action }} --auto-approve"